name: firebase.auth_phone_ng
description: Phone auth sample using AngularDart
version: 1.0.0
authors:
- Jana Moudra <jana.moudra@gmail.com>
- Kevin Moore <kevmoo@google.com>
homepage: https://github.com/firebase/firebase-dart
environment:
  sdk: '>=1.21.0 <2.0.0'
dependencies:
  angular: '^4.0.0'
transformers:
  - angular:
      entry_points:
          - web/main.dart